package migrations

import (
	"github.com/pocketbase/pocketbase/core"
	m "github.com/pocketbase/pocketbase/migrations"
)

func init() {
	m.Register(func(app core.App) error {
		jsonData := `[
			{
				"createRule": "",
				"deleteRule": "",
				"fields": [
					{
						"autogeneratePattern": "[a-z0-9]{15}",
						"hidden": false,
						"id": "text3208210256",
						"max": 15,
						"min": 15,
						"name": "id",
						"pattern": "^[a-z0-9]+$",
						"presentable": false,
						"primaryKey": true,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "fx0bgsho",
						"max": 0,
						"min": 0,
						"name": "game_code",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"hidden": false,
						"id": "fe7wfdrv",
						"max": null,
						"min": null,
						"name": "roundDuration",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "bool3528574234",
						"name": "isStarted",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "bool"
					},
					{
						"hidden": false,
						"id": "autodate2990389176",
						"name": "created",
						"onCreate": true,
						"onUpdate": false,
						"presentable": false,
						"system": false,
						"type": "autodate"
					},
					{
						"hidden": false,
						"id": "autodate3332085495",
						"name": "updated",
						"onCreate": true,
						"onUpdate": true,
						"presentable": false,
						"system": false,
						"type": "autodate"
					}
				],
				"id": "wc90g85v7uuln21",
				"indexes": [],
				"listRule": "",
				"name": "games",
				"system": false,
				"type": "base",
				"updateRule": "",
				"viewRule": ""
			},
			{
				"createRule": "",
				"deleteRule": "",
				"fields": [
					{
						"autogeneratePattern": "[a-z0-9]{15}",
						"hidden": false,
						"id": "text3208210256",
						"max": 15,
						"min": 15,
						"name": "id",
						"pattern": "^[a-z0-9]+$",
						"presentable": false,
						"primaryKey": true,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "e7xmmbgt",
						"max": 0,
						"min": 0,
						"name": "username",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"cascadeDelete": false,
						"collectionId": "wc90g85v7uuln21",
						"hidden": false,
						"id": "1srnymqn",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "game_id",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"hidden": false,
						"id": "vse1ozz7",
						"name": "is_host",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "bool"
					},
					{
						"hidden": false,
						"id": "number1177347317",
						"max": null,
						"min": null,
						"name": "position",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "kcby59pi",
						"maxSelect": 1,
						"maxSize": 5242880,
						"mimeTypes": null,
						"name": "avatar",
						"presentable": false,
						"protected": false,
						"required": false,
						"system": false,
						"thumbs": null,
						"type": "file"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text1716930793",
						"max": 0,
						"min": 0,
						"name": "color",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"hidden": false,
						"id": "autodate2990389176",
						"name": "created",
						"onCreate": true,
						"onUpdate": false,
						"presentable": false,
						"system": false,
						"type": "autodate"
					},
					{
						"hidden": false,
						"id": "autodate3332085495",
						"name": "updated",
						"onCreate": true,
						"onUpdate": true,
						"presentable": false,
						"system": false,
						"type": "autodate"
					}
				],
				"id": "8z2mvm3t0hc1nku",
				"indexes": [],
				"listRule": "",
				"name": "users",
				"system": false,
				"type": "base",
				"updateRule": "",
				"viewRule": ""
			},
			{
				"createRule": "",
				"deleteRule": "",
				"fields": [
					{
						"autogeneratePattern": "[a-z0-9]{15}",
						"hidden": false,
						"id": "text3208210256",
						"max": 15,
						"min": 15,
						"name": "id",
						"pattern": "^[a-z0-9]+$",
						"presentable": false,
						"primaryKey": true,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"cascadeDelete": false,
						"collectionId": "8z2mvm3t0hc1nku",
						"hidden": false,
						"id": "relation2375276105",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "user_id",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_232317621",
						"hidden": false,
						"id": "relation2858238006",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "story_id",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"cascadeDelete": false,
						"collectionId": "wc90g85v7uuln21",
						"hidden": false,
						"id": "relation3834632453",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "game_id",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"hidden": false,
						"id": "file2573967335",
						"maxSelect": 1,
						"maxSize": 0,
						"mimeTypes": [],
						"name": "drawing",
						"presentable": false,
						"protected": false,
						"required": false,
						"system": false,
						"thumbs": [],
						"type": "file"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text1659857976",
						"max": 0,
						"min": 0,
						"name": "prompt",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"hidden": false,
						"id": "bool2404849967",
						"name": "is_drawing",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "bool"
					},
					{
						"hidden": false,
						"id": "autodate2990389176",
						"name": "created",
						"onCreate": true,
						"onUpdate": false,
						"presentable": false,
						"system": false,
						"type": "autodate"
					},
					{
						"hidden": false,
						"id": "autodate3332085495",
						"name": "updated",
						"onCreate": true,
						"onUpdate": true,
						"presentable": false,
						"system": false,
						"type": "autodate"
					}
				],
				"id": "pbc_953189830",
				"indexes": [],
				"listRule": "",
				"name": "turns",
				"system": false,
				"type": "base",
				"updateRule": "",
				"viewRule": ""
			},
			{
				"createRule": "",
				"deleteRule": "",
				"fields": [
					{
						"autogeneratePattern": "[a-z0-9]{15}",
						"hidden": false,
						"id": "text3208210256",
						"max": 15,
						"min": 15,
						"name": "id",
						"pattern": "^[a-z0-9]+$",
						"presentable": false,
						"primaryKey": true,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"cascadeDelete": false,
						"collectionId": "8z2mvm3t0hc1nku",
						"hidden": false,
						"id": "relation2908382924",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "starter_id",
						"presentable": false,
						"required": true,
						"system": false,
						"type": "relation"
					},
					{
						"cascadeDelete": false,
						"collectionId": "wc90g85v7uuln21",
						"hidden": false,
						"id": "relation3834632453",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "game_id",
						"presentable": false,
						"required": true,
						"system": false,
						"type": "relation"
					},
					{
						"hidden": false,
						"id": "autodate2990389176",
						"name": "created",
						"onCreate": true,
						"onUpdate": false,
						"presentable": false,
						"system": false,
						"type": "autodate"
					},
					{
						"hidden": false,
						"id": "autodate3332085495",
						"name": "updated",
						"onCreate": true,
						"onUpdate": true,
						"presentable": false,
						"system": false,
						"type": "autodate"
					}
				],
				"id": "pbc_232317621",
				"indexes": [],
				"listRule": "",
				"name": "stories",
				"system": false,
				"type": "base",
				"updateRule": "",
				"viewRule": ""
			},
			{
				"createRule": null,
				"deleteRule": null,
				"fields": [
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text3208210256",
						"max": 0,
						"min": 0,
						"name": "id",
						"pattern": "^[a-z0-9]+$",
						"presentable": false,
						"primaryKey": true,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"cascadeDelete": false,
						"collectionId": "wc90g85v7uuln21",
						"hidden": false,
						"id": "_clone_IR3G",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "game_id",
						"presentable": false,
						"required": true,
						"system": false,
						"type": "relation"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_232317621",
						"hidden": false,
						"id": "relation2858238006",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "story_id",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"cascadeDelete": false,
						"collectionId": "8z2mvm3t0hc1nku",
						"hidden": false,
						"id": "relation960592715",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "starter_user_id",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"hidden": false,
						"id": "_clone_Aa7d",
						"max": null,
						"min": null,
						"name": "starter_position",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"hidden": false,
						"id": "json2008733210",
						"maxSize": 1,
						"name": "turns_taken",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "json"
					},
					{
						"hidden": false,
						"id": "json3528647380",
						"maxSize": 1,
						"name": "total_players",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "json"
					},
					{
						"cascadeDelete": false,
						"collectionId": "8z2mvm3t0hc1nku",
						"hidden": false,
						"id": "relation1709242679",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "next_user_id",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"hidden": false,
						"id": "_clone_1fCK",
						"max": null,
						"min": null,
						"name": "next_user_position",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"cascadeDelete": false,
						"collectionId": "8z2mvm3t0hc1nku",
						"hidden": false,
						"id": "relation4221711427",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "prev_user_id",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"hidden": false,
						"id": "_clone_PFDT",
						"max": null,
						"min": null,
						"name": "prev_user_position",
						"onlyInt": false,
						"presentable": false,
						"required": false,
						"system": false,
						"type": "number"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "_clone_9zg1",
						"max": 0,
						"min": 0,
						"name": "prev_prompt",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"hidden": false,
						"id": "_clone_ZL2e",
						"maxSelect": 1,
						"maxSize": 0,
						"mimeTypes": [],
						"name": "prev_drawing",
						"presentable": false,
						"protected": false,
						"required": false,
						"system": false,
						"thumbs": [],
						"type": "file"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_953189830",
						"hidden": false,
						"id": "relation1132691295",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "prev_turn_id",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					}
				],
				"id": "pbc_2132018881",
				"indexes": [],
				"listRule": "",
				"name": "progress",
				"system": false,
				"type": "view",
				"updateRule": null,
				"viewQuery": "SELECT\n  (ROW_NUMBER() OVER()) as id,\n  stories.game_id AS game_id,\n  stories.id AS story_id,\n  users_starter.id AS starter_user_id,\n  users_starter.position AS starter_position,\n  COALESCE(turn_counts.taken, 0) AS turns_taken,\n  player_counts.total_players AS total_players,\n  next_user.id AS next_user_id,\n  next_user.position AS next_user_position,\n  prev_user.id AS prev_user_id,\n  prev_user.position AS prev_user_position,\n  turns.prompt AS prev_prompt,\n  turns.drawing AS prev_drawing,\n  turns.id AS prev_turn_id\nFROM stories\nJOIN users AS users_starter\n  ON users_starter.id = stories.starter_id\nJOIN (\n  SELECT users.game_id AS game_id, COUNT(*) AS total_players\n  FROM users\n  GROUP BY users.game_id\n) AS player_counts\n  ON player_counts.game_id = stories.game_id\nLEFT JOIN (\n  SELECT turns.story_id AS story_id, COUNT(*) AS taken\n  FROM turns\n  GROUP BY turns.story_id\n) AS turn_counts\n  ON turn_counts.story_id = stories.id\n-- changed to LEFT JOIN + added guard so completed stories yield NULL next_user\nLEFT JOIN users AS next_user\n  ON next_user.game_id = stories.game_id\n AND COALESCE(turn_counts.taken, 0) < player_counts.total_players\n AND next_user.position = (\n   (users_starter.position + COALESCE(turn_counts.taken, 0))\n   % player_counts.total_players\n )\nJOIN users AS prev_user\n  ON prev_user.game_id = stories.game_id\n AND prev_user.position = (\n   (users_starter.position + COALESCE(turn_counts.taken, 0) - 1)\n   % player_counts.total_players\n )\nLEFT JOIN turns\n  ON turns.story_id = stories.id\n AND turns.user_id = prev_user.id;\n",
				"viewRule": ""
			},
			{
				"createRule": null,
				"deleteRule": null,
				"fields": [
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "text3208210256",
						"max": 0,
						"min": 0,
						"name": "id",
						"pattern": "^[a-z0-9]+$",
						"presentable": false,
						"primaryKey": true,
						"required": true,
						"system": true,
						"type": "text"
					},
					{
						"cascadeDelete": false,
						"collectionId": "wc90g85v7uuln21",
						"hidden": false,
						"id": "_clone_WGw0",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "game_id",
						"presentable": false,
						"required": true,
						"system": false,
						"type": "relation"
					},
					{
						"cascadeDelete": false,
						"collectionId": "8z2mvm3t0hc1nku",
						"hidden": false,
						"id": "_clone_0QUY",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "starter_id",
						"presentable": false,
						"required": true,
						"system": false,
						"type": "relation"
					},
					{
						"cascadeDelete": false,
						"collectionId": "pbc_953189830",
						"hidden": false,
						"id": "relation525310089",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "turn_id",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"cascadeDelete": false,
						"collectionId": "8z2mvm3t0hc1nku",
						"hidden": false,
						"id": "_clone_eNlg",
						"maxSelect": 1,
						"minSelect": 0,
						"name": "turn_user_id",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "relation"
					},
					{
						"hidden": false,
						"id": "json3706167346",
						"maxSize": 1,
						"name": "turn_number",
						"presentable": false,
						"required": false,
						"system": false,
						"type": "json"
					},
					{
						"autogeneratePattern": "",
						"hidden": false,
						"id": "_clone_1miq",
						"max": 0,
						"min": 0,
						"name": "prompt",
						"pattern": "",
						"presentable": false,
						"primaryKey": false,
						"required": false,
						"system": false,
						"type": "text"
					},
					{
						"hidden": false,
						"id": "_clone_v3I9",
						"maxSelect": 1,
						"maxSize": 0,
						"mimeTypes": [],
						"name": "drawing",
						"presentable": false,
						"protected": false,
						"required": false,
						"system": false,
						"thumbs": [],
						"type": "file"
					}
				],
				"id": "pbc_3796656622",
				"indexes": [],
				"listRule": "",
				"name": "results",
				"system": false,
				"type": "view",
				"updateRule": null,
				"viewQuery": "SELECT\n    (ROW_NUMBER() OVER()) as id,\n    stories.game_id,\n    stories.starter_id,\n    turns.id as turn_id,\n    turns.user_id as turn_user_id,\n    (\n      (turn_number.position - starter_position.position + player_counts.total_players)\n      % player_counts.total_players\n    ) AS turn_number,\n    turns.prompt,\n    turns.drawing\nFROM stories\nJOIN turns ON turns.story_id = stories.id\nLEFT JOIN (\n  SELECT users.id, users.position\n  From users\n) AS starter_position ON stories.starter_id = starter_position.id\nLEFT JOIN (\n  SELECT users.id, users.position\n  From users\n) AS turn_number ON turns.user_id = turn_number.id\nJOIN (\n  SELECT users.game_id AS game_id, COUNT(*) AS total_players\n  FROM users\n  GROUP BY users.game_id\n) AS player_counts\n  ON player_counts.game_id = stories.game_id",
				"viewRule": ""
			}
		]`

		return app.ImportCollectionsByMarshaledJSON([]byte(jsonData), false)
	}, func(app core.App) error {
		return nil
	})
}
